import { type NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../components/Navbar";
import { useSession } from "next-auth/react";

import { api } from "../utils/api";
import { Text, Box, Center } from "@chakra-ui/react";

const Home: NextPage = () => {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>t3 chakra starter template</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        
        <Center>
        {session ? (
          <Box pt="5">
            <Text>Logged in as: {session!.user.name} - {session!.user.email}</Text>
          </Box>
        ) : (
          <Box pt="5">
            <Text>not authenticated. please sign in to continue.</Text>
          </Box>
        )}
        </Center>

      </main>
    </>
  )
}

export default Home;

