import { type NextPage } from "next";
import Head from "next/head";

import { Navbar } from "../components/Navbar";
import { Main } from "../components/Main"
import { api } from "../utils/api";

import { useSession } from "next-auth/react";

import { Box, Center, Text } from "@chakra-ui/react";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>t3 chakra starter template</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />

        <Center>
          {session ? (
            <Main />
          ) : (
            <Box pt="5">
              <Text>not authenticated. please sign in to continue.</Text>
            </Box>
          )}
        </Center>
      </main>
    </>
  );
};

export default Home;
